#!/bin/sh
########################################################################
# Begin atd
# Atd artalan sürecini başlatma servisi
# Description : Atd artalan sürecini başlat
#
# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.2
#
########################################################################

### BEGIN INIT INFO
# Provides:            atd
# Required-Start:      $time
# Should-Start:        
# Required-Stop:       
# Should-Stop:         
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   atd daemon
# Description:         Daha sonra yürütmek için sıraya alınmış işleri çalıştır
# X-LFS-Provided-By:   BLFS / LFS 7.2
### END INIT INFO

. /etc/rc.d/functions

#$LastChangedBy: bdubbs $
#$Date: 2012-05-09 15:19:23 -0500 (Wed, 09 May 2012) $

case "$1" in
   start)
      log_info_msg "Atd başlatılıyor..."
      start_daemon /usr/sbin/atd
      evaluate_retval
      ;;

   Baslat)
      log_info_msg "Atd başlatılıyor..."
      start_daemon /usr/sbin/atd
      evaluate_retval
      ;;

   stop)
      log_info_msg "Atd durduruluyor..."
      killproc /usr/sbin/atd
      evaluate_retval
      ;;

   durdur)
      log_info_msg "Atd durduruluyor..."
      killproc /usr/sbin/atd
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   ybaslat)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc /usr/sbin/atd
      ;;
   durum)
      statusproc /usr/sbin/atd
      ;;

   *)
      echo "Kullanımı: $0 {baslat|durdur|ybaslat|durum}"
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End atd

