#!/bin/sh
#
# /etc/rc.d/bumblebeed: start/stop bumblebeed
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/bumblebeed
OPTS="--daemon"

case $1 in
start)
	$SSD --start --exec $PROG -- $OPTS
	;;
	
	baslat)
	$SSD --start --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --retry 10 --exec $PROG
	;;
	
	durdur)
	$SSD --stop --retry 10 --exec $PROG
	;;
restart)
	$0 stop
	sleep 1
	$0 start
	;;
	
	ybaslat)
	$0 stop
	sleep 1
	$0 start
	;;
	
status)
	$SSD --status --exec $PROG
	case $? in
	0) echo "$PROG, pid $(pidof $PROG) ile yürütülüyor" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG çalışmıyor" ;;
	4) echo "Program durumu belirlenemiyor" ;;
	esac
	;;
	
durum)
	$SSD --status --exec $PROG
	case $? in
	0) echo "$PROG , pid $(pidof $PROG) ile yürütülüyor" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG çalışmıyor" ;;
	4) echo "Program durumu belirlenemiyor" ;;
	esac
	;;
*)
	echo "Kullanımı: $0 [baslat|durdur|ybaslat|durum]"
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
