#!/bin/sh
#
# mount-iphone.sh
# This script attempts to mount or unmount the first connected ipod/iphone.
# Usage: ./mount-iphone.sh [mount | umount | echo_serial]
# It should be dash-friendly
#
# Written by Mohamed Ahmed, Dec 2010
#
# Refactored and extended by David Emerson, Feb 2012
#
# 2017-04-04   DaveSp   In case more than one Apple device is attached via USB,
#                       "awk '/iSerial" now only matches when a serial number is
#                       present.
#
# You can configure send_msg to use either a console echo, or notify-send.
# notify-send is part of the debian package, libnotify-bin
# The apple pictures in /usr/share/pixmaps are part of the gnome-desktop-data package
#
# uncomment the following if you want to see the mount command used:
# show_mount_cmd=1

# you can uncomment this line to see all the commands sh executes:
# set -x

show_msg ()
{
  # notify-send -t 4000 -u normal "mount-iphone" "$1" -i "/usr/share/pixmaps/apple-$2.png"
  echo "$1" >&2
}

get_device_ids ()
{
  # get the Apple vendor id (idVendor) from lsusb
  idVendor=$(lsusb -v 2>/dev/null | awk '/idVendor.*Apple/{print $2; exit}')
  [ -z "$idVendor" ] && { show_msg "Apple aygıtı bulunamadı" "red"; exit 1; }
  # get the device serial number (iSerial)
  iSerial=$(lsusb -v -d $idVendor: 2>/dev/null | awk '/iSerial\s+\S+\s+\S/{print $3; exit}')
  [ -z "$iSerial" ] && { show_msg "Apple aygıtının seri numarası bulunamadı $idVendor" "red"; exit 1; }
}

is_mounted ()
{
  gvfs-mount -l | grep -i "mount.*$1" >/dev/null
}

mount_iphone ()
{
  [ -z $show_mount_cmd ] || echo gvfs-mount afc://$1/ >&2
  if gvfs-mount afc://$1/; then
    show_msg "$1 seri nolu iphone bağlandı" "green"
  else
    show_msg "iphone bağlama hatası" "red"
    exit 1
  fi
}

unmount_iphone ()
{
  ## now gvfs unmount the device
  [ -z $show_mount_cmd ] || echo gvfs-mount -u afc://$1/ >&2
  if gvfs-mount -u afc://$1/; then
    show_msg "$1 seri nolu iphone bağlantısı kesildi" "red"
  else
    show_msg "iphone bağlama hatası" "red"
    exit 1
  fi
}

case $1 in
  mount)
    get_device_ids
    is_mounted && { show_msg "$iSerial zaten bağlı" 'green'; exit; }
    mount_iphone $iSerial
    ;;
  bagla)
    get_device_ids
    is_mounted && { show_msg "$iSerial zaten bağlı" 'green'; exit; }
    mount_iphone $iSerial
    ;;
  umount|unmount)
    get_device_ids
    is_mounted || { show_msg "$iSerial bağlı değil" 'red'; exit; }
    unmount_iphone $iSerial
    ;;

  ayir)
    get_device_ids
    is_mounted || { show_msg "$iSerial bağlı değil" 'red'; exit; }
    unmount_iphone $iSerial
    ;;

  echo_serial)
    get_device_ids
    echo $iSerial
    ;;

  serino)
    get_device_ids
    echo $iSerial
    ;;
  '')
    get_device_ids
    is_mounted && show_msg "$iSerial bağlandı" 'green' || show_msg "$iSerial bağlanmadı" 'red'
    ;;
  *)
    echo "Kullanımı: $0 [mount | umount | echo_serial]"
    echo "Kullanımı: $0 [bagla | ayir | seri_no]"
    exit 1
    ;;
esac

exit 0
