#!/bin/sh
########################################################################
# Begin saslauthd
#
# Description : Cyrus SASL Boot Script
#
# Authors     : Armin K. <krejzi@email.com>
#
# Version     : BLFS SVN
#
# Notes       : Not enabled by default.
#
########################################################################

### BEGIN INIT INFO
# Provides:            saslauthd
# Required-Start:      $local_fs
# Required-Stop:       $local_fs
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   saslauthd startup script
# Description:         This script starts the saslauthd daemon. It is
#                      configured using the file /etc/sysconfig/saslauthd.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /etc/rc.d/functions

START="no"
AUTHMECH=""
OPTIONS=""

if [ -f "/etc/sysconfig/saslauthd" ]; then
   . /etc/sysconfig/saslauthd
fi

case "${1}" in
   start)

      if [ "$START" != "yes" ]; then
         MSG="Configure saslauthd in /etc/sysconfig/saslauthd"
         log_warning_msg "$MSG and set START to yes"
         exit 0
      fi

      if [ -z "$AUTHMECH" ]; then
         MSG="Kimlik doğrulama mekanizmasını seçmeniz gerekiyor"
         log_warning_msg "$MSG /etc/sysconfig/saslauthd"
         exit 0
      fi

      if [ ! -d /var/run/saslauthd ]; then
         install -d -o root -g root -m 711 /var/run/saslauthd
      fi

      log_info_msg "SASL Authentication Daemon saslauthd başlatılıyor"
      start_daemon /usr/bin/saslauthd -a $AUTHMECH $OPTIONS
      evaluate_retval
      ;;

   stop)
      log_info_msg "SASL Authentication Daemon saslauthd durduruluyor"
      killproc /usr/bin/saslauthd
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   status)
      statusproc /usr/bin/saslauthd
      ;;

   *)
      echo "Kullanımı: ${0} {start|stop|restart|status}"
      exit 1
      ;;
 esac
exit 0

# End saslauthd
