#!/bin/sh
########################################################################
# Begin scriptname
#
# Description :
#
# Authors     :
#
# Version     : LFS x.x
#
# Notes       :
#
########################################################################

### BEGIN INIT INFO
# Provides:            template
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:
# Default-Stop:
# Short-Description:
# Description:
# X-LFS-Provided-By:
### END INIT INFO

. /etc/rc.d/functions

case "${1}" in
   start)
      log_info_msg "Başlatılıyor..."
      start_daemon fully_qualified_path
      ;;

   stop)
      log_info_msg "Durduruluyor..."
      killproc fully_qualified_path
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Kullanımı: ${0} {start|stop|restart}"
      exit 1
      ;;
esac

exit 0

# End scriptname
