#!/bin/sh
########################################################################
# Begin acpid
#
# Description : ACPI olay arka plan programı önyükleme komut dosyası
#
# Author      : Igor Živković <contact@igor-zivkovic.from.hr>
#
# Version     : BLFS SVN
#
########################################################################

### BEGIN INIT INFO
# Provides:            acpid
# Required-Start:      $remote_fs $syslog
# Required-Stop:       $remote_fs $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Gelişmiş Yapılandırma ve Güç Arabirimi olay arka planını başlatır
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /etc/rc.d/functions

#$LastChangedBy: igor $
#$Date: 2013-07-10 17:04:20 -0500 (Wed, 10 Jul 2013) $

case "$1" in
   baslat)
      log_info_msg "ACPI event daemon baslatılıyor..."
      start_daemon /usr/bin/acpid
      sleep 1
      pidofproc -p "/run/acpid.pid" > /dev/null
      evaluate_retval
      ;;

   durdur)
      log_info_msg "ACPI event daemon durduruluyor..."
      killproc -p "/run/acpid.pid" /usr/bin/acpid
      evaluate_retval
      ;;

   ybaslat)
      $0 stop
      sleep 1
      $0 start
      ;;

   durum)
      statusproc /usr/bin/acpid
      ;;

   *)
      echo "Kullanımı: $0 {baslat|durdur|ybaslat|durum}"
      exit 1
      ;;
esac

# End acpid
