#!/bin/sh
########################################################################
# Begin alsa
#
# Description : ALSA ayarlarını geri yükleyin ve saklayın
#
# Author      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : BLFS SVN
#
########################################################################

### BEGIN INIT INFO
# Provides:            alsa
# Required-Start:      
# Should-Start:
# Required-Stop:       sendsignals
# Should-Stop:
# Default-Start:       S
# Default-Stop:        0 1 6
# Short-Description:   ALSA karıştırıcı ayarlarını geri yükleyin ve saklayın.
# Description:        ALSA karıştırıcı ayarlarını varsayılan olarak geri yükler ve saklar
#                      location: /var/lib/alsa/asound.state.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /etc/rc.d/functions

#$LastChangedBy: igor $
#$Date: 2013-07-25 04:50:36 -0500 (Thu, 25 Jul 2013) $

case "$1" in
   baslat)
      log_info_msg "ALSA başlatılıyor...    Sesler onarılıyor.."
      /usr/sbin/alsactl restore
      evaluate_retval
      ;;

   durdur)
      log_info_msg "ALSA durduruluyor...    Sesler kaydediliyor..."
      /usr/sbin/alsactl store
      evaluate_retval
      ;;

   *)
      echo "Kullanımı: $0 {baslat|durdur}"
      exit 1
      ;;
esac

# End alsa
