#!/bin/sh
# Begin /etc/rc.d/init.d/lightdm

### BEGIN INIT INFO
# Provides:            lightdm
# Required-Start:      $local_fs
# Should-Start:        $remote_fs $syslog
# Required-Stop:       $local_fs
# Should-Stop:         $remote_fs $syslog
# Default-Start:       5
# Default-Stop:        0 1 2 3 4 6
# Short-Description:   Starts lightdm.
# Description:         Starts lightdm daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /etc/rc.d/functions
#[ -e /opt/xorg/bin/X ] && . /etc/profile 

BIN_FILE="/usr/bin/lightdm"

#$LastChangedBy: bdubbs $
#$Date: 2018-01-05 12:17:22 -0600 (Fri, 05 Jan 2018) $

case $1 in
   baslat)
        log_info_msg "Lightdm başlatılıyor..."
        start_daemon $BIN_FILE &
        evaluate_retval
        ;;

   durdur)
        log_info_msg "Lightdm durduruluyor..."
        killproc $BIN_FILE
        evaluate_retval
        ;;

   ybaslat)
        $0 stop
        sleep 2
        $0 start
        ;;

   durum)
        statusproc ${BIN_FILE}
        ;;

   *)
        echo "Kullanımı: $0 [baslat|durdur|ybaslat|durum]"
        exit 1
        ;;
esac

# End /etc/rc.d/init.d/lightdm

