#!/bin/sh
#
# /etc/rc.d/slim: start/stop slim
#
. /etc/rc.d/functions

case $1 in
baslat)
	log_info_msg "Yerel ayarlar eklendi..."
    yerel_ayar
    log_info_msg "SLIM başlatılıyor..."
	/usr/bin/slim -d
	;;
durdur)
	log_info_msg "SLIM durduruluyor..."
	killall /usr/bin/slim
	;;
ybaslat)
	log_info_msg "SLIM yebaşlatılıyor..."
	$0 stop
	sleep 2
	$0 start
	;;
*)
	echo "Kullanımı: $0 [baslat|durdur|ybaslat]"
	;;
esac

# End of file
