#!/bin/sh
########################################################################
# Begin swap
#
# Description : Swap Control Script
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#               DJ Lucas - dj@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            swap
# Required-Start:      udev
# Should-Start:        modules
# Required-Stop:       localnet
# Should-Stop:
# Default-Start:       S
# Default-Stop:        0 6
# Short-Description:   Mounts and unmounts swap partitions.
# Description:         Mounts and unmounts swap partitions defined in
#                      /etc/fstab.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /etc/rc.d/functions

case "${1}" in
   baslat)
      log_info_msg "Tüm swap dosyaları/bölümleri aktif ediliyor..."
      swapon -a
      evaluate_retval
      ;;

   durum)
      log_info_msg "Tüm swap dosyaları/bölümleri pasif ediliyor..."
      swapoff -a
      evaluate_retval
      ;;

   ybaslat)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   durum)
      log_success_msg "Takas durumu alınıyor." 
      swapon -s
      ;;

   *)
      echo "Kullanımı: ${0} {baslat|durdur|ybaslat|durum}"
      exit 1
      ;;
esac

exit 0

# End swap
